### ISSUE TITLE
Arreglar Menú

### ISSUE THREAD

**Issue by danielhernandezs** [BrandSpa/acn_africa#3]
Moni arregla el menú @MoniLop

**Comment by alesanabriav7** [comment]
![fav2x](https://cloud.githubusercontent.com/assets/1097809/23971333/891aa8ee-099b-11e7-9ade-764cca573329.png)

**Comment by danielhernandezs** [comment]
Prueba desde el correo



  <https://mailtrack.io/> Enviado con Mailtrack
<https://mailtrack.io/install?source=signature&lang=es&referral=daniel@brandspa.com&idSignature=23>

2017-03-15 16:22 GMT-05:00 Alejandro Sanabria V <notifications@github.com>:
