### ISSUE TITLE
Bug componente de pago

### ISSUE THREAD

**Issue by danielhernandezs** [BrandSpa/acn_africa#5]
hay dos issues en los Landings de International con el iFrame de Stripe, en español e inglés; abajo los print-screen:
![image](https://cloud.githubusercontent.com/assets/26444890/23971904/d1173156-099d-11e7-8d05-d311682cb330.png)

![image](https://cloud.githubusercontent.com/assets/26444890/23971913/d76cf644-099d-11e7-8750-77abd1742fff.png)

![image](https://cloud.githubusercontent.com/assets/26444890/23971922/dd3c68fc-099d-11e7-8bfd-180251008c34.png)

**Comment by alesanabriav7** [comment]
Solucionado en ingles y español... ![screen shot 2017-03-15 at 4 44 21 pm](https://cloud.githubusercontent.com/assets/1097809/23972143/acf9c2e2-099e-11e7-915c-8f371dbff761.png)
