### ISSUE TITLE
Traducción Francés

### ISSUE THREAD

**Issue by danielhernandezs** [BrandSpa/acn_africa#7]

**Comment by juanbrandspa** [comment]
Falta traducción de:
- [ ] Texto Introducción
- [ ] Texto download pdf
- [ ] Texto:
DESCARGA EL VIA CRUCIS POR AFRICA Y ACOMPÁÑA TUS HERMANOS DE ESTE CONTINENTE CON TU ORACIÓN EN ESTA CUARESMA.
- [ ] Texto: #VIACRUCISPORAFRICA

**Comment by MoniLop** [comment]
Done
